# Generated by Django 3.2.9 on 2021-11-11 09:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhar_number',
            field=models.CharField(max_length=16, unique=True, validators=[users.models.validateAadharNo]),
        ),
    ]
