# Generated by Django 3.2.9 on 2021-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('location', models.TextField()),
                ('pin_code', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
